version: "3.7"

services:
  mozzi_database:
    container_name: mozzi_database
    image: mariadb
    environment:
        MYSQL_ROOT_PASSWORD: mozzi
        MYSQL_DATABASE: mozzi
        MYSQL_USER: mozzi
        MYSQL_PASSWORD: mozzi
    ports:
      - 3306:3306


  mozzi:
      image: openjdk:8
      container_name: mozzi
      build:
        context: .
        dockerfile: Dockerfile
      environment:
        SPRING_PROFILES_ACTIVE: 'dockercompose'
        MYSQL_ROOT_PASSWORD: mozzi
        MYSQL_DATABASE: mozzi
        MYSQL_USER: mozzi
        MYSQL_PASSWORD: mozzi
      ports:
        - 8080:8080
      restart: always
      links:
        - mozzi_database
      depends_on:
        - mozzi_database